spring:
  application:
    name: Devlink-backend
  security:
    oauth2:
      client:
        registration:
          epicgames:
            client-id: ${EPIC_GAMES_CLIENT_ID}
            client-secret: ${EPIC_GAMES_CLIENT_SECRET}
            scope: basic_profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Epic Games
            client-authentication-method: post
        provider:
          epicgames:
            authorization-uri: https://www.epicgames.com/id/authorize
            token-uri: https://api.epicgames.dev/epic/oauth/v2/token
            user-info-uri: https://api.epicgames.dev/epic/oauth/v2/userinfo
            user-name-attribute: sub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devlink
    username: root
    password: 1234
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
