spring:
  application:
    name: Devlink-backend
  security:
    oauth2:
      client:
        registration:
          epicgames:
            client-id: ${EPIC_GAMES_CLIENT_ID}
            client-secret: ${EPIC_GAMES_CLIENT_SECRET}
            scope: basic_profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Epic Games
            client-authentication-method: post