spring:
  application:
    name: Devlink-backend
  security:
    oauth2:
      client:
        registration:
          epicgames:
            client-id: ${EPIC_GAMES_CLIENT_ID}
            client-secret: ${EPIC_GAMES_CLIENT_SECRET}
            scope: basic_profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Epic Games
            client-authentication-method: post
        provider:
          epicgames:
            authorization-uri: https://www.epicgames.com/id/authorize
            token-uri: https://api.epicgames.dev/epic/oauth/v2/token
            user-info-uri: https://api.epicgames.dev/epic/oauth/v2/userinfo
            user-name-attribute: sub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://125.132.216.190:15531/devlink
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  data:
    mongodb:
      host: 125.132.216.190
      port: 15532
      database: devlink
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-operation-id: true # 메서드 ID 표시
    default-model-expand-depth: 1 # 모델 깊이
    doc-expansion: none # 기본 확장 상태 (none, list, full)
    show-extensions: true # 확장 정보 표시
    operationsSorter: alpha # 알파벳순 정렬
    tagsSorter: alpha # 태그 알파벳순 정렬
logging:
  level:
    org:
      springframework:
        security: DEBUG